# -*- mode: ruby -*-
# vi: set ft=ruby :

# To enable rsync folder share change to false
$vm_mem = "2048"
$vb_gui = false

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box   = "devstack"

  config.vm.define "dev" do |node|
      node.vm.synced_folder ".", "/vagrant"

      node.vm.provider "virtualbox" do |vb|
          vb.memory = $vm_mem
          vb.gui = $vb_gui
      end

      # Add private network with fixed IP 172.31.255.254
      node.vm.network "private_network", ip: "172.31.255.254"

      node.vm.provision "shell", inline: "/vagrant/deploy/deploy.sh", privileged: false
      node.vm.provision "shell", inline: "pushd /vagrant/docker; docker-compose stop; docker-compose up -d; popd", privileged: false, run: "always"
  end
end
